### ISSUE TITLE
exception on the server

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Python-Translators#37]
```
[Mon Mar 12 15:56:31.663237 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448] mod_wsgi (pid=28184): Exception occurred processing WSGI script '/home/mircea/zee/http/api/zeeguu_api.wsgi'.
[Mon Mar 12 15:56:31.665368 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448] Traceback (most recent call last):
[Mon Mar 12 15:56:31.665516 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1997, in __call__
[Mon Mar 12 15:56:31.665529 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     return self.wsgi_app(environ, start_response)
[Mon Mar 12 15:56:31.665548 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1985, in wsgi_app
[Mon Mar 12 15:56:31.665559 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     response = self.handle_exception(e)
[Mon Mar 12 15:56:31.665577 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/usr/local/lib/python3.6/site-packages/Flask_Cors-3.0.2-py3.6.egg/flask_cors/extension.py", line 161, in wrapped_function
[Mon Mar 12 15:56:31.665587 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     return cors_after_request(app.make_response(f(*args, **kwargs)))
[Mon Mar 12 15:56:31.665605 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1540, in handle_exception
[Mon Mar 12 15:56:31.665616 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     reraise(exc_type, exc_value, tb)
[Mon Mar 12 15:56:31.665633 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/_compat.py", line 33, in reraise
[Mon Mar 12 15:56:31.665643 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     raise value
[Mon Mar 12 15:56:31.665660 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1982, in wsgi_app
[Mon Mar 12 15:56:31.665673 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     response = self.full_dispatch_request()
[Mon Mar 12 15:56:31.665691 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1614, in full_dispatch_request
[Mon Mar 12 15:56:31.665701 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     rv = self.handle_user_exception(e)
[Mon Mar 12 15:56:31.665735 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/usr/local/lib/python3.6/site-packages/Flask_Cors-3.0.2-py3.6.egg/flask_cors/extension.py", line 161, in wrapped_function
[Mon Mar 12 15:56:31.665744 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     return cors_after_request(app.make_response(f(*args, **kwargs)))
[Mon Mar 12 15:56:31.665761 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1517, in handle_user_exception
[Mon Mar 12 15:56:31.665770 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     reraise(exc_type, exc_value, tb)
[Mon Mar 12 15:56:31.665787 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/_compat.py", line 33, in reraise
[Mon Mar 12 15:56:31.665796 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     raise value
[Mon Mar 12 15:56:31.665812 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1612, in full_dispatch_request
[Mon Mar 12 15:56:31.665822 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     rv = self.dispatch_request()
[Mon Mar 12 15:56:31.665838 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/usr/local/lib/python3.6/site-packages/Flask-0.12.2-py3.6.egg/flask/app.py", line 1598, in dispatch_request
[Mon Mar 12 15:56:31.665847 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     return self.view_functions[rule.endpoint](**req.view_args)
[Mon Mar 12 15:56:31.665864 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/usr/local/lib/python3.6/site-packages/Flask_MonitoringDashboard-1.10.5-py3.6.egg/flask_monitoringdashboard/measurement.py", line 88, in wrapper
[Mon Mar 12 15:56:31.665874 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     return func(*args, **kwargs)
[Mon Mar 12 15:56:31.665890 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/usr/local/lib/python3.6/site-packages/Flask_MonitoringDashboard-1.10.5-py3.6.egg/flask_monitoringdashboard/measurement.py", line 60, in wrapper
[Mon Mar 12 15:56:31.665900 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     result = func(*args, **kwargs)
[Mon Mar 12 15:56:31.665916 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/home/mircea/zee/http/api/zeeguu_api/api/utils/route_wrappers.py", line 43, in wrapped_view
[Mon Mar 12 15:56:31.665926 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     response = flask.make_response(view(*args, **kwargs))
[Mon Mar 12 15:56:31.665942 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/home/mircea/zee/http/api/zeeguu_api/api/utils/route_wrappers.py", line 29, in wrapped_view
[Mon Mar 12 15:56:31.665951 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     return view(*args, **kwargs)
[Mon Mar 12 15:56:31.665967 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/home/mircea/zee/http/api/zeeguu_api/api/translate_and_bookmark.py", line 163, in translate_and_bookmark
[Mon Mar 12 15:56:31.665977 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     minimal_context, query = minimize_context(context_str, from_lang_code, word_str)
[Mon Mar 12 15:56:31.665994 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/home/mircea/zee/http/api/zeeguu_api/api/translate_and_bookmark.py", line 123, in minimize_context
[Mon Mar 12 15:56:31.666003 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     _query = TranslationQuery.for_word_occurrence(word_str, context_str, 1, 3)
[Mon Mar 12 15:56:31.666029 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]   File "/usr/local/lib/python3.6/site-packages/python_translators-0.1-py3.6.egg/python_translators/translation_query.py", line 46, in for_word_occurrence
[Mon Mar 12 15:56:31.666039 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448]     before_context, after_context = context.split(query, word_index_for_query)
[Mon Mar 12 15:56:31.666079 2018] [wsgi:error] [pid 28184:tid 140675533518592] [remote 206.166.91.2:49448] ValueError: not enough values to unpack (expected 2, got 1)

```

and some of the translation logs":
```

        FROM_CACHE: False
        TIME_PASSED: 1411
        TRANSLATOR_NAME: CompositeParallel(Google - without context, Google - with context)
        CONTEXT_PROCESSORS: []
        RESPONSE_PROCESSORS: []
        PRE_QUERY: 'stand'
        PRE_BEFORE_CONTEXT: 'Al blijft het COC wel bezorgd over de afspraken die in de onderhandelingen met de ChristenUnie tot'
        PRE_AFTER_CONTEXT: ' gaan komen.'
        POST_QUERY: 'stand'
        POST_BEFORE_CONTEXT: 'Al blijft het COC wel bezorgd over de afspraken die in de onderhandelingen met de ChristenUnie tot'
        POST_AFTER_CONTEXT: ' gaan komen.'
        TRANSLATIONS: ['Condition']
        QUALITIES: [80]
        SERVICE_NAMES: ['Google']
2017-07-01 15:56:45,182 - app - INFO -
        EVENT: translation_result
        FROM_CACHE: False
        TIME_PASSED: 583
        TRANSLATOR_NAME: Google - without context
        CONTEXT_PROCESSORS: ['remove_all_context', 'escape_html']
        RESPONSE_PROCESSORS: ['unescape_html']
        PRE_QUERY: 'principieel'
        PRE_BEFORE_CONTEXT: 'Zo is de ChristenUnie'
        PRE_AFTER_CONTEXT: ' tegen het meerouderplan, bedoeld om de positie van bepaalde homoseksuele ouders te verbeteren.'
        POST_QUERY: 'principieel'
        POST_BEFORE_CONTEXT: ''
        POST_AFTER_CONTEXT: ''
        TRANSLATIONS: ['In principle']
        QUALITIES: [80]
        SERVICE_NAMES: ['Google']
2017-07-01 15:56:45,184 - app - INFO -
        EVENT: translation_result
        FROM_CACHE: False
        TIME_PASSED: 584
        TRANSLATOR_NAME: Google - with context
        CONTEXT_PROCESSORS: ['remove_unnecessary_sentences', 'remove_unnecessary_conjunctions', 'escape_html']
        RESPONSE_PROCESSORS: ['unescape_html']
        PRE_QUERY: 'principieel'
        PRE_BEFORE_CONTEXT: 'Zo is de ChristenUnie'
        PRE_AFTER_CONTEXT: ' tegen het meerouderplan, bedoeld om de positie van bepaalde homoseksuele ouders te verbeteren.'
        POST_QUERY: 'principieel'
        POST_BEFORE_CONTEXT: 'Zo is de ChristenUnie'
        POST_AFTER_CONTEXT: ' tegen het meerouderplan, bedoeld om de positie van bepaalde homoseksuele ouders te verbeteren.'
        TRANSLATIONS: ['principle']
        QUALITIES: [70]
        SERVICE_NAMES: ['Google']

```

**Comment by mircealungu** [comment]
can't replicate. will close for now.
